<?php
/**
 * TL_ROOT/system/modules/dlh_googlemaps/languages/cs/default.php 
 * 
 * Contao extension: dlh_googlemaps 1.1.0 stable 
 * Czech translation file 
 * 
 * Copyright : 2011 de la Haye Kommunikationsdesign 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Christian de la Haye (christian), http://www.delahaye.de 
 * Translator: Tomas Petrlik (frogzone), www.frogzone.cz 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['dlh_googlemaps']['0'] = "Google Mapa";
$GLOBALS['TL_LANG']['MOD']['dlh_googlemaps']['1'] = "Zde můžete spravovat své Google Mapy.";
$GLOBALS['TL_LANG']['CTE']['dlh_googlemaps']['0'] = "Google Mapa";
$GLOBALS['TL_LANG']['CTE']['dlh_googlemaps']['1'] = "Integrovat Google Mapu.";
$GLOBALS['TL_LANG']['dlh_googlemaps']['labels']['noscript'] = "Google Mapa";
$GLOBALS['TL_LANG']['dlh_googlemaps']['labels']['routingLink'] = "Plánování";
$GLOBALS['TL_LANG']['dlh_googlemaps']['labels']['routingLabel'] = "? z vaší adresy:";
$GLOBALS['TL_LANG']['dlh_googlemaps']['labels']['routingSubmit'] = "ok";
 
?>
