<?php
/**
 * TL_ROOT/system/modules/dlh_googlemaps/languages/cs/tl_content.php 
 * 
 * Contao extension: dlh_googlemaps 1.1.0 stable 
 * Czech translation file 
 * 
 * Copyright : 2011 de la Haye Kommunikationsdesign 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Christian de la Haye (christian), http://www.delahaye.de 
 * Translator: Tomas Petrlik (frogzone), www.frogzone.cz 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_content']['dlh_googlemap']['0'] = "Google Mapa";
$GLOBALS['TL_LANG']['tl_content']['dlh_googlemap']['1'] = "Prosím, vyberte Google Mapu.";
$GLOBALS['TL_LANG']['tl_content']['dlh_googlemap_zoom']['0'] = "Přiblížení";
$GLOBALS['TL_LANG']['tl_content']['dlh_googlemap_zoom']['1'] = "Prosím, zadejte přiblížení mapy.";
$GLOBALS['TL_LANG']['tl_content']['dlh_googlemap_size']['0'] = "Zadejte šířku a výšku";
$GLOBALS['TL_LANG']['tl_content']['dlh_googlemap_size']['1'] = "Prosím, zadejte šířku a výšku mapy.";
$GLOBALS['TL_LANG']['tl_content']['dlh_googlemap_static']['0'] = "Použít statickou mapu";
$GLOBALS['TL_LANG']['tl_content']['dlh_googlemap_static']['1'] = "Namísto normální Google mapy, zobrazit statickou mapu.";
$GLOBALS['TL_LANG']['tl_content']['dlh_googlemap_url']['0'] = "Adresu odkazu";
$GLOBALS['TL_LANG']['tl_content']['dlh_googlemap_url']['1'] = "Zadejte prosím webovou adresu (http:// ...), nebo vložte tag.";
 
?>
