<?php
/**
 * TL_ROOT/system/modules/dlh_googlemaps/languages/cs/tl_dlh_googlemaps_elements.php 
 * 
 * Contao extension: dlh_googlemaps 1.1.0 stable 
 * Czech translation file 
 * 
 * Copyright : 2011 de la Haye Kommunikationsdesign 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Christian de la Haye (christian), http://www.delahaye.de 
 * Translator: Tomas Petrlik (frogzone), www.frogzone.cz 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['title']['0'] = "Název";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['title']['1'] = "Název prvku mapy.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['type']['0'] = "Typ";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['type']['1'] = "Typ prvku mapy.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['published']['0'] = "Publikováno";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['published']['1'] = "Prvek je publikován.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['singleCoords']['0'] = "Zeměpisné souřadnice";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['singleCoords']['1'] = "Zadejte prosím zeměpisné souřadnice prvku.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['multiCoords']['0'] = "Vícero souřadnic";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['multiCoords']['1'] = "Zadejte prosím víc souřadnic pro prvek. Mnohoúhelníky se automaticky uzavřou.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['radius']['0'] = "Rádius v metrech";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['radius']['1'] = "Zadejte prosím rádius v metrech.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['strokeColor']['0'] = "Barva čáry";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['strokeColor']['1'] = "Zadejte prosím barvu čar.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['strokeWeight']['0'] = "Tloušťka čáry";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['strokeWeight']['1'] = "Zadejte prosím tloušťku čáry v pixelech.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['strokeOpacity']['0'] = "Průhlednost čáry";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['strokeOpacity']['1'] = "Zadejte prosím průhlednost čáry.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['fillColor']['0'] = "Vybarvit";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['fillColor']['1'] = "Zadejte prosím požadovanou barvu výplně.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['fillOpacity']['0'] = "Průhlednost výplně";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['fillOpacity']['1'] = "Zadejte prosím průhlednost výplně.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['markerAction']['0'] = "Reakce na kliknutí";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['markerAction']['1'] = "Zde se rozhodnete, jak budou prvky reagovat na kliknutí.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['popupInfoWindow']['0'] = "Automaticky otevřít informační okno";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['popupInfoWindow']['1'] = "Otvírat informační okno automaticky?";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['infoWindow']['0'] = "Informační okno";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['infoWindow']['1'] = "Zadejte prosím obsah informačního okna. Vkladací tagy jsou podporovány.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['infoWindowAnchor']['0'] = "Pozice ukotvení informačního okna";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['infoWindowAnchor']['1'] = "Pozice informačního okna může být změněna za pomoci šipek Doleva, nahoru. Např. Posuňte informační okno o 5 pixelů vlevo a 10 pixelů nahoru.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['url']['0'] = "Odkaz";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['url']['1'] = "Zadejte prosím url (včetně http://) nebo si vyberte stránku Contao";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['linkTitle']['0'] = "Název odkazu";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['linkTitle']['1'] = "Tento text se zobrazí jako tip na klikacím prvku.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['target']['0'] = "Otevřít v novém okně.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['target']['1'] = "Otevřít odkaz v novém okně.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['bounds']['0'] = "Zeměpisné souřadnice jihozápad / severovýchod";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['bounds']['1'] = "Zadejte prosím souřadnice prvku jako 2 párové souřadnice.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['overlaySRC']['0'] = "Soubor";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['overlaySRC']['1'] = "Vyberte si prosím obrázek (gif, jpg nebo png), který překryje mapu v rámci vybrané oblasti.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['markerShowTitle']['0'] = "Zobrazit název";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['markerShowTitle']['1'] = "Zobrazit název značky jako tip.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['markerType']['0'] = "Typ značky";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['markerType']['1'] = "Můžete použít standardní Google značky nebo si vytvořit vlastní.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['useRouting']['0'] = "Využít plánování tras";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['useRouting']['1'] = "Plánovač tras v Google mapě může být formulářem přímo propojen s informačním oknem.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['routingAddress']['0'] = "Adresa pro plánování";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['routingAddress']['1'] = "Zadejte prosím cíl cesty. V případě, že zůstane pole prázdné, budou použity zeměpisné souřadnice.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['iconSRC']['0'] = "Soubor pro ikonu";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['iconSRC']['1'] = "Vyberte si prosím obrázek (gif, jpg nebo png), který bude použit pro ikonu.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['iconSize']['0'] = "Rozměry šířka x výška";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['iconSize']['1'] = "Rozměry ikony.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['iconAnchor']['0'] = "Pozice ukotvení ikony";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['iconAnchor']['1'] = "Pozici ikony můžete změnit šipkami Nalevo, Nahoru. Např. 5, 10 přesune ikonu 5 pixelů vlevo a 10 pixelů nahoru.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['hasShadow']['0'] = "Stín";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['hasShadow']['1'] = "Ikona má stín";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['shadowSRC']['0'] = "Soubor pro stín";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['shadowSRC']['1'] = "Vyberte si prosím obrázek (png je nejlepší), který bude použit jako stín.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['shadowSize']['0'] = "Rozměry šířka x výška";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['shadowSize']['1'] = "Rozměry stínu. Zvláštní pozice použitá ikonou je využita i pro stín.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['zIndex']['0'] = "z-Index";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['zIndex']['1'] = "Vodorovná pozice prvku k mapě.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['parameter']['0'] = "Další parametry";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['parameter']['1'] = "Zde můžete zadat další parametry pro prvky mapy.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['import']['0'] = "Import";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['import']['1'] = "Import souboru souřadnic.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['importfile']['0'] = "Zdrojový soubor";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['importfile']['1'] = "Vyberte soubor CSV pro import.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['new']['0'] = "Nový prvek";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['new']['1'] = "Přidat nový prvek mapy.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['edit']['0'] = "Upravit prvek";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['edit']['1'] = "Upravit prvek ID %s.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['copy']['0'] = "Kopírovat prvek";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['copy']['1'] = "Kopírovat prvek ID %s.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['delete']['0'] = "Vymazat prvek";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['delete']['1'] = "Vymazat prvek ID %s.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['show']['0'] = "Podrobnosti prvku";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['show']['1'] = "Zobrazt podrobnosti prvku ID %s.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['toggle']['0'] = "Publikovat prvek";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['toggle']['1'] = "Publikovat prvek ID %s.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['title_legend'] = "Název a typ";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['element_legend'] = "Konfigurace prvku";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['parameter_legend'] = "Další parametry";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['references']['MARKER'] = "Značka (w, w/o routing)";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['references']['INFOWINDOW'] = "Informační okno";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['references']['RECTANGLE'] = "Obdelník";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['references']['CIRCLE'] = "Kruh";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['references']['POLYLINE'] = "Poly line";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['references']['POLYGON'] = "Mnohoúhelník";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['references']['GROUND_OVERLAY'] = "Základní překrytí";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['references']['NONE'] = "Bez reakce";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['references']['LINK'] = "Přímý odkaz na značku";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['references']['INFO'] = "Otevřít informační okno";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['references']['SIMPLE'] = "Výchozí Google značka";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['references']['ICON'] = "Vlastní ikona";
 
?>
