<?php
/**
 * TL_ROOT/system/modules/dlh_googlemaps/languages/cs/tl_dlh_googlemaps.php 
 * 
 * Contao extension: dlh_googlemaps 1.1.0 stable 
 * Czech translation file 
 * 
 * Copyright : 2011 de la Haye Kommunikationsdesign 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Christian de la Haye (christian), http://www.delahaye.de 
 * Translator: Tomas Petrlik (frogzone), www.frogzone.cz 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['title']['0'] = "Název";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['title']['1'] = "Název Google Mapy.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['center']['0'] = "Souřadnice středu mapy";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['center']['1'] = "Prosím, zadejte souřadnice středu mapy. (např.: 48.856846,2.351024). Souřadnice mohou být generovány z adresy (s.b.).";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['geocoderAddress']['0'] = "Adresa pro střed mapy";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['geocoderAddress']['1'] = "Pokud pole souřadnice středu mapy je prazdné a zde uvedete adresu bude střed mapy automaticky generován z této adresy.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['geocoderCountry']['0'] = "Země";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['geocoderCountry']['1'] = "Upřesněte zemi, ve které se nachází hledaná adresa pro střed mapy.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['mapSize']['0'] = "Zadejte šířku a výšku";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['mapSize']['1'] = "Prosím, zadejte šířku a výšku mapy.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['zoom']['0'] = "Přiblížení";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['zoom']['1'] = "Prosím, zadejte přiblížení mapy.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['mapTypeId']['0'] = "Standardní zobrazení";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['mapTypeId']['1'] = "Prosím, nastavte standardní pohled na mapu.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['mapTypesAvailable']['0'] = "Volitelné zobrazení";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['mapTypesAvailable']['1'] = "Prosím, upřesněte volitelné zobrazení na mapě.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['streetViewControl']['0'] = "Street View";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['streetViewControl']['1'] = "Zobrazit Street View.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['draggable']['0'] = "Posouvání myší";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['draggable']['1'] = "Mapa může být přemístěna pomocí myši.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['staticMapNoscript']['0'] = "Statická mapa jako alternativní";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['staticMapNoscript']['1'] = "Pokud není povolen JavaScript, bude namísto normální Google mapy, zobrazena statická mapa.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['disableDoubleClickZoom']['0'] = "Přiblížení na dvojklik";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['disableDoubleClickZoom']['1'] = "Deaktivovat přiblížení dvojklikem na mapě.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['scrollwheel']['0'] = "Přiblížení kolečkem myši";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['scrollwheel']['1'] = "Povolit přiblížení kolečkem myši.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['sensor']['0'] = "Senzor";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['sensor']['1'] = "Aplikace využívá senzory (viz Googgle API).";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['useMapTypeControls']['0'] = "Použití ovládacích prvků typu mapy";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['useMapTypeControls']['1'] = "Uveďte, zda se prvky typu mapy mají použít.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['mapTypeControlStyle']['0'] = "Typ ovládacích prvků mapy";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['mapTypeControlStyle']['1'] = "Uveďte prosím formátování prvku.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['mapTypeControlPos']['0'] = "Pozice";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['mapTypeControlPos']['1'] = "Prosím upřesněte pozici prvku na mapě.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['useNavigationControl']['0'] = "Použijte navigační ovládací prvky";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['useNavigationControl']['1'] = "Uveďte prosím, jestli je použit nějaký prvek.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['navigationControlStyle']['0'] = "Typ navigačních ovladacích prvků";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['navigationControlStyle']['1'] = "Upřesněte prosím formátování prvku.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['navigationControlPos']['0'] = "Pozice";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['navigationControlPos']['1'] = "Prosím upřesněte pozici prvku na mapě.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['useScaleControl']['0'] = "Použijte ovládací prvky měřítka";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['useScaleControl']['1'] = "Uveďte prosím, jestli je použit nějaký prvek.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['scaleControlStyle']['0'] = "Typy ovládacích prvků měřítka";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['scaleControlStyle']['1'] = "Upřesněte prosím formátování prvku.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['scaleControlPos']['0'] = "Pozice";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['scaleControlPos']['1'] = "Prosím upřesněte pozici prvku na mapě.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['parameter']['0'] = "Další parametry";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['parameter']['1'] = "Zde můžete zadat další parametry mapy.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['new']['0'] = "Nová Google mapa";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['new']['1'] = "Přidat novou Google mapu.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['edit']['0'] = "Upravit Google mapu";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['edit']['1'] = "Upravit Google mapy ID %s.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['copy']['0'] = "Kopírovat Google Mapu";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['copy']['1'] = "Kopírovat Google mapy  ID %s.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['delete']['0'] = "Vymazat Google mapu";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['delete']['1'] = "Vymazat Google mapy ID %s.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['show']['0'] = "Podrobnosti Google mapy";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['show']['1'] = "Zobrazit podrobnosti Google mapy ID %s.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['editheader']['0'] = "Upravit nastavení Google mapy";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['editheader']['1'] = "Upravit nastavení Google mapy ID %s.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['title_legend'] = "Název a základní informace";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['maptype_legend'] = "Typ mapy a vlastnosti";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['maptypecontrols_legend'] = "Typ ovládacích prvků mapy";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['navigationcontrol_legend'] = "Navigační ovládací prvky";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['scalecontrol_legend'] = "Ovládací prvky měřítka";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['parameter_legend'] = "Další parametry";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['references']['DEFAULT'] = "Výchozí";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['references']['HYBRID'] = "Hybridní";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['references']['ROADMAP'] = "Mapa";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['references']['SATELLITE'] = "Satelitní";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['references']['TERRAIN'] = "Terénní";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['references']['DROPDOWN_MENU'] = "Rolovací menu";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['references']['HORIZONTAL_BAR'] = "Vodorovná lišta";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['references']['ANDROID'] = "Android";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['references']['SMALL'] = "Malá verze";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['references']['ZOOM_PAN'] = "Velká verze";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['references']['noCurl'] = "Není možné geokódování - chybějící CURL.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['references']['noCoords'] = "Není možné geokódování.";
 
?>
