<?php
/**
 * TL_ROOT/system/modules/dlh_googlemaps/languages/cs/tl_module.php 
 * 
 * Contao extension: dlh_googlemaps 1.1.0 stable 
 * Czech translation file 
 * 
 * Copyright : 2011 de la Haye Kommunikationsdesign 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Christian de la Haye (christian), http://www.delahaye.de 
 * Translator: Tomas Petrlik (frogzone), www.frogzone.cz 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['dlh_googlemap']['0'] = "Google mapa";
$GLOBALS['TL_LANG']['tl_module']['dlh_googlemap']['1'] = "Vybete si prosím Google mapu";
$GLOBALS['TL_LANG']['tl_module']['dlh_googlemap_zoom']['0'] = "Přiblížení";
$GLOBALS['TL_LANG']['tl_module']['dlh_googlemap_zoom']['1'] = "Prosím, zadejte přiblížení mapy.";
$GLOBALS['TL_LANG']['tl_module']['dlh_googlemap_size']['0'] = "Rozměry šířka x výška";
$GLOBALS['TL_LANG']['tl_module']['dlh_googlemap_size']['1'] = "Zde můžete změnit nastavení rozměrů mapy.";
$GLOBALS['TL_LANG']['tl_module']['dlh_googlemap_static']['0'] = "Použít nepohyblivou mapu";
$GLOBALS['TL_LANG']['tl_module']['dlh_googlemap_static']['1'] = "Místo normální Google mapy se zobrazi omezená (statická)mapa.";
$GLOBALS['TL_LANG']['tl_module']['dlh_googlemap_url']['0'] = "Adresa odkazu";
$GLOBALS['TL_LANG']['tl_module']['dlh_googlemap_url']['1'] = "Zadejte prosím adresu webu (včetně http://...) nebo vložte tag.";
 
?>
