<?php
/**
 * TL_ROOT/system/modules/dlh_googlemaps/languages/fr/default.php 
 * 
 * Contao extension: dlh_googlemaps 1.0.0 stable 
 * French translation file 
 * 
 * Copyright : 2010 de la Haye Kommunikationsdesign 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Christian de la Haye (christian), http://www.delahaye.de 
 * Translator: Jérôme DENIS (irongomme), http://www.sweb-developpement.com 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['dlh_googlemaps']['0'] = "Google Maps";
$GLOBALS['TL_LANG']['MOD']['dlh_googlemaps']['1'] = "Ici vous pouvez administrer vos Google Maps.";
$GLOBALS['TL_LANG']['CTE']['dlh_googlemaps']['0'] = "Google Map";
$GLOBALS['TL_LANG']['CTE']['dlh_googlemaps']['1'] = "Integrer une Google Map.";
$GLOBALS['TL_LANG']['dlh_googlemaps']['labels']['noscript'] = "Google Map";
$GLOBALS['TL_LANG']['dlh_googlemaps']['labels']['routingLink'] = "Itinéraire";
$GLOBALS['TL_LANG']['dlh_googlemaps']['labels']['routingLabel'] = "? depuis votre adresse:";
$GLOBALS['TL_LANG']['dlh_googlemaps']['labels']['routingSubmit'] = "ok";
 
?>
