<?php
/**
 * TL_ROOT/system/modules/dlh_googlemaps/languages/fr/tl_dlh_googlemaps.php 
 * 
 * Contao extension: dlh_googlemaps 1.0.0 stable 
 * French translation file 
 * 
 * Copyright : 2010 de la Haye Kommunikationsdesign 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Christian de la Haye (christian), http://www.delahaye.de 
 * Translator: Jérôme DENIS (irongomme), http://www.sweb-developpement.com 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['title']['0'] = "Titre";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['title']['1'] = "Titre de la Google Map.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['center']['0'] = "Géo-coordonnées";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['center']['1'] = "Veuillez saisir les géo-coordonnées du centre de la carte (ex: 48.856846,2.351024). Les coordonnées peuvent être générées depuis l'adresse.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['geocoderAddress']['0'] = "Adresse pour la géolocalisation";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['geocoderAddress']['1'] = "Dans le cas où le champs ´géo-coordonnées´ est vide, cette adresse servira à générer les géo-coordonnées à l'enregistrement.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['geocoderCountry']['0'] = "Pays";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['geocoderCountry']['1'] = "Indiquez le pays dans lequel l'adresse doit être trouvée.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['mapSize']['0'] = "Dimensions largeur x hauteur";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['mapSize']['1'] = "Dimensions de la Google Map. Cette valeur peut être redéfini plus tard.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['zoom']['0'] = "Niveau de zoom";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['zoom']['1'] = "La carte débutera avec ce niveau de zoom. Cette valeur peut être redéfini plus tard.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['mapTypeId']['0'] = "Type de carte initial";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['mapTypeId']['1'] = "Indiquez l'apparence initiale de la carte.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['mapTypesAvailable']['0'] = "Types de cartes disponibles";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['mapTypesAvailable']['1'] = "Indiquez les types de cartes disponibles.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['streetViewControl']['0'] = "Street View";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['streetViewControl']['1'] = "Street View est activé.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['draggable']['0'] = "Défilement";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['draggable']['1'] = "La carte peut être déplacé à la souris.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['staticMapNoscript']['0'] = "Carte statique de secours";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['staticMapNoscript']['1'] = "Si javascript n'est pas activé, une carte statique (restreinte) doit apparaitre à la place.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['disableDoubleClickZoom']['0'] = "Désactiver le zoom au double clic";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['disableDoubleClickZoom']['1'] = "En double cliquant la carte, aucun zoom n'est appliqué.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['scrollwheel']['0'] = "Zoom avec la molette de la souris";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['scrollwheel']['1'] = "Le zoom avec la molette de la souris est activé.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['sensor']['0'] = "Capteur";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['sensor']['1'] = "L'application utilise des capteurs (voir Google API)";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['useMapTypeControls']['0'] = "Utiliser les controles de type de carte";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['useMapTypeControls']['1'] = "Veuillez indiquer si ces éléments doivent etre utilisés.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['mapTypeControlStyle']['0'] = "Type des controles de type de carte";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['mapTypeControlStyle']['1'] = "Veuillez indiquer le formattage de l'élément.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['mapTypeControlPos']['0'] = "Position";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['mapTypeControlPos']['1'] = "Veuillez indiquer la position de l'élément sur la carte.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['useNavigationControl']['0'] = "Utiliser les controles de navigation";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['useNavigationControl']['1'] = "Veuillez indiquer si ces éléments doivent etre utilisés.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['navigationControlStyle']['0'] = "Type de controles de navigation";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['navigationControlStyle']['1'] = "Veuillez indiquer le formattage de l'élément.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['navigationControlPos']['0'] = "Position";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['navigationControlPos']['1'] = "Veuillez indiquer la position de l'élément sur la carte.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['useScaleControl']['0'] = "Utiliser le controle d'ajustement";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['useScaleControl']['1'] = "Veuillez indiquer si ces éléments doivent etre utilisés.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['scaleControlStyle']['0'] = "Type de controles d'ajustement";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['scaleControlStyle']['1'] = "Veuillez indiquer le formattage de l'élément.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['scaleControlPos']['0'] = "Position";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['scaleControlPos']['1'] = "Veuillez indiquer la position de l'élément sur la carte.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['parameter']['0'] = "Paramètres additionnels";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['parameter']['1'] = "Ici vous pouvez indiquer des paramètres additionnels pour la carte.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['new']['0'] = "Nouvelle Google Map";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['new']['1'] = "Ajouter une nouvelle Google Map";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['edit']['0'] = "Editer Google Map";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['edit']['1'] = "Edit la Google Map ID %s";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['copy']['0'] = "Dupliquer Google Map";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['copy']['1'] = "Dupliquer la Google Map ID %s";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['delete']['0'] = "Supprimer Google Map";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['delete']['1'] = "Supprimer la Google Map ID %s";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['show']['0'] = "Détails de la Google Map";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['show']['1'] = "Voir les détails de la Google Map ID %s";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['editheader']['0'] = "Editer les paramétres Google Map";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['editheader']['1'] = "Editer les paramétres de la  Google Map ID %s";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['title_legend'] = "Titre et bases";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['maptype_legend'] = "Type de carte et comportement";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['maptypecontrols_legend'] = "Controles de type de carte";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['navigationcontrol_legend'] = "Controles de navigation";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['scalecontrol_legend'] = "Controles d'ajustement";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['parameter_legend'] = "Paramètres additionnels";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['references']['DEFAULT'] = "Par défaut";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['references']['HYBRID'] = "Hybride";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['references']['ROADMAP'] = "Plan";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['references']['SATELLITE'] = "Satellite";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['references']['TERRAIN'] = "Terrain";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['references']['DROPDOWN_MENU'] = "Menu déroulant";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['references']['HORIZONTAL_BAR'] = "Barre horizontale";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['references']['ANDROID'] = "Android";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['references']['SMALL'] = "Petite version";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['references']['ZOOM_PAN'] = "Grande version";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['references']['noCurl'] = "Géolocalisation impossible - il manque CURL";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps']['references']['noCoords'] = "Géolocalisation impossible.";
 
?>
