<?php
/**
 * TL_ROOT/system/modules/dlh_googlemaps/languages/fr/tl_dlh_googlemaps_elements.php 
 * 
 * Contao extension: dlh_googlemaps 1.0.0 stable 
 * French translation file 
 * 
 * Copyright : 2010 de la Haye Kommunikationsdesign 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Christian de la Haye (christian), http://www.delahaye.de 
 * Translator: Jérôme DENIS (irongomme), http://www.sweb-developpement.com 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['title']['0'] = "Titre";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['title']['1'] = "Titre de l'élément de la carte";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['type']['0'] = "Type";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['type']['1'] = "Type d'élément de carte.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['published']['0'] = "Publié";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['published']['1'] = "L'élément est publié.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['singleCoords']['0'] = "Géo-coordonnées";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['singleCoords']['1'] = "Veuillez saisir les géo-coordonnées de l'élément.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['multiCoords']['0'] = "Géo-coordonnées multiples";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['multiCoords']['1'] = "Veuillez saisir les multiples géo-coordonnées pour cet élément. Les polygones se ferment automatiquement.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['radius']['0'] = "Rayon en mètres";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['radius']['1'] = "Veuillez saisir le rayon du cercle en mètres.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['strokeColor']['0'] = "Couleur de ligne";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['strokeColor']['1'] = "Veuillez saisir la couleur des lignes.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['strokeWeight']['0'] = "Epaisseur de ligne";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['strokeWeight']['1'] = "Veuillez saisir l'épaisseur des lignes en pixels.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['strokeOpacity']['0'] = "Opacité de ligne";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['strokeOpacity']['1'] = "Veuillez saisir l'opacité des lignes";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['fillColor']['0'] = "Couleur de fond";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['fillColor']['1'] = "Veuillez saisir la couleur de remplissage.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['fillOpacity']['0'] = "Opacité du remplissage";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['fillOpacity']['1'] = "Veuillez saisir l'opacité pour la couleur de remplissage.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['markerAction']['0'] = "Action au clic";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['markerAction']['1'] = "Ici vous choisissez comment l'élément doit réagir au clic.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['popupInfoWindow']['0'] = "Ouvrir l'infobulle automatiquement";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['popupInfoWindow']['1'] = "L'infobulle doit-elle s'ouvrir automatiquement ?";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['infoWindow']['0'] = "Infobulle";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['infoWindow']['1'] = "Veuillez entrer le contenu pour l'infobulle. Les tags d'insertion sont pris en charge.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['infoWindowAnchor']['0'] = "Position de l'ancre de l'infobulle";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['infoWindowAnchor']['1'] = "La position de l'infobulle peut etre modifiés grace aux coordonnées GAUCHE, HAUT. Ex: 5,10 déplace l'infobulle de 5px à gauche et 10 pixels en haut.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['url']['0'] = "Lien";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['url']['1'] = "veuillez saisir une url (avec http://) ou choisissez une page Contao.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['linkTitle']['0'] = "Titre du lien";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['linkTitle']['1'] = "Ce texte est affiché comme infobulle par l'élément cliquable.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['target']['0'] = "Ouvrir dans une nouvelle fenètre";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['target']['1'] = "Ouvir le lien dans une nouvelle fenètre du navigateur.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['bounds']['0'] = "Géo-coordonnées sud-ouest/nord-est";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['bounds']['1'] = "Veuillez saisir les coordonnées de l'élément à l'aide de deux paires de coordonnées.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['overlaySRC']['0'] = "Fichier";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['overlaySRC']['1'] = "Veuillez choisir un fichier image (gif, jpg ou png), qui se placera comme calque au dessus de la zone choisie sur la carte.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['markerShowTitle']['0'] = "Montrer le titre";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['markerShowTitle']['1'] = "Montrer le titre du marqueur en tant qu'infobulle.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['markerType']['0'] = "Type de marqueur";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['markerType']['1'] = "Vous pouvez utiliser les marqueurs Google standards ou des icônes individuels.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['useRouting']['0'] = "Utiliser l'itinéraire";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['useRouting']['1'] = "L'itinéraire Google Maps peut être directement lié à l'infobulle par le biais d'un formulaire.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['routingAddress']['0'] = "Adresse pour l'itinéraire";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['routingAddress']['1'] = "Veuillez saisir l'adresse de destination pour l'itinéraire. Si le champs est vide, les géo-coordonnées seront utiliés.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['iconSRC']['0'] = "Fichier pour l'icone.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['iconSRC']['1'] = "Veuillez choisir un fichier image (gif, jpg ou png) à utiliser en tant qu'icône.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['iconSize']['0'] = "Dimensions largeur x hauteur";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['iconSize']['1'] = "Dimensions de l'icone.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['iconAnchor']['0'] = "Position de l'ancre de l'icone";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['iconAnchor']['1'] = "La position de l'icone peut etre modifiés grace aux coordonnées GAUCHE, HAUT. Ex: 5,10 déplace l'icone de 5px à gauche et 10 pixels en haut.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['hasShadow']['0'] = "Utiliser une ombre";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['hasShadow']['1'] = "L'icone possède une ombre";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['shadowSRC']['0'] = "Fichier pour l'ombre";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['shadowSRC']['1'] = "Veuillez choisir une image (le format png est le meilleur choix) devant être utilisé comme ombre.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['shadowSize']['0'] = "Dimensions largeur x hauteur";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['shadowSize']['1'] = "Dimensions de l'ombre. Une position spéciale pour l'icône sera également utilisée par l'ombre.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['zIndex']['0'] = "z-Index";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['zIndex']['1'] = "Position horizontale de l'élément relative à la carte.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['parameter']['0'] = "Paramètres additionnels";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['parameter']['1'] = "Ici, vous pouvez saisir des paramètres additionnels pour les éléments de la carte.";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['new']['0'] = "Nouvel élément";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['new']['1'] = "Ajoute un nouvel élément";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['edit']['0'] = "Editer élément";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['edit']['1'] = "Editer l'élément ID %s";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['copy']['0'] = "Copier élément";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['copy']['1'] = "Copier l'élément ID %s";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['delete']['0'] = "Supprimer élément";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['delete']['1'] = "Supprimer l'élément ID %s";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['show']['0'] = "Détails élément";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['show']['1'] = "Voir les détails de l'élément ID %s";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['toggle']['0'] = "Publier élément";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['toggle']['1'] = "Pulier l'élément ID %s";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['title_legend'] = "Titre et type";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['element_legend'] = "Configuration de l'élément";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['parameter_legend'] = "Paramètres additionnels";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['references']['MARKER'] = "Marqueur (w, w/o routing)";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['references']['INFOWINDOW'] = "Infobulle";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['references']['RECTANGLE'] = "Rectangle";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['references']['CIRCLE'] = "Cercle";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['references']['POLYLINE'] = "Multi lignes";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['references']['POLYGON'] = "Polygone";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['references']['GROUND_OVERLAY'] = "Calque";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['references']['NONE'] = "Aucune action";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['references']['LINK'] = "Lien direct sur le marqueur";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['references']['INFO'] = "Ouvrir l'infobulle";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['references']['SIMPLE'] = "Marqueur Google par défaut";
$GLOBALS['TL_LANG']['tl_dlh_googlemaps_elements']['references']['ICON'] = "Icone individuel";
 
?>
