<?php
/**
 * TL_ROOT/system/modules/dlh_googlemaps/languages/fr/tl_module.php 
 * 
 * Contao extension: dlh_googlemaps 1.0.0 stable 
 * French translation file 
 * 
 * Copyright : 2010 de la Haye Kommunikationsdesign 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Christian de la Haye (christian), http://www.delahaye.de 
 * Translator: Jérôme DENIS (irongomme), http://www.sweb-developpement.com 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['dlh_googlemap']['0'] = "Google Map";
$GLOBALS['TL_LANG']['tl_module']['dlh_googlemap']['1'] = "Veuillez choisir une Google Map.";
$GLOBALS['TL_LANG']['tl_module']['dlh_googlemap_zoom']['0'] = "Niveau de zoom.";
$GLOBALS['TL_LANG']['tl_module']['dlh_googlemap_zoom']['1'] = "Ici vous pouvez redéfinir le niveau de zoom du module qui sera utilisé uniquement par cette implémentation.";
$GLOBALS['TL_LANG']['tl_module']['dlh_googlemap_size']['0'] = "Dimensions largeur x hauteur";
$GLOBALS['TL_LANG']['tl_module']['dlh_googlemap_size']['1'] = "Ici vous pouvez redéfinir les dimensions de la carte du module, qui seront utilisées uniquement par cette implémentation.";
$GLOBALS['TL_LANG']['tl_module']['dlh_googlemap_static']['0'] = "Utiliser une carte statique";
$GLOBALS['TL_LANG']['tl_module']['dlh_googlemap_static']['1'] = "A la place d'une Google Map standard, une carte statique (restreinte) peut être affichée.";
$GLOBALS['TL_LANG']['tl_module']['dlh_googlemap_url']['0'] = "Adresse du lien";
$GLOBALS['TL_LANG']['tl_module']['dlh_googlemap_url']['1'] = "Veuillez saisir une adresse web (http://...) ou un tag d'insertion.";
 
?>
